version: '3.9'

services:
  epc:
    build:
      context: .
      dockerfile: ./Dockerfile_epc
    image: naposto/srsepc
    container_name: epc
    hostname: epc
    privileged: true
    volumes:
      - type: bind
        source: ./test/docker_files/user_db.csv
        target: /conf/user_db.csv
      - type: bind
        source: ./test/docker_files/epc.conf
        target: /conf/epc.conf
    networks:
      srsnet:
        ipv4_address: "172.18.0.2"
  
  enb1:
    build:
      context: .
      dockerfile: ./Dockerfile_enb
    image: naposto/srsenb
    container_name: enb1
    hostname: enb1
    privileged: true
    depends_on:
      - epc
    volumes:
      - type: bind
        source: ./test/docker_files/rr.conf
        target: /conf/rr.conf
      - type: bind
        source: ./test/docker_files/enb.conf
        target: /conf/enb.conf
    networks:
      srsnet:
        ipv4_address: "172.18.0.3"          
  
  enb2:
    build:
      context: .
      dockerfile: ./Dockerfile_enb        
    image: naposto/srsenb
    container_name: enb2
    hostname: enb2
    privileged: true
    depends_on:
      - epc
    volumes:
      - type: bind
        source: ./test/docker_files/rr.conf
        target: /conf/rr.conf
      - type: bind
        source: ./test/docker_files/enb2.conf
        target: /conf/enb.conf
    networks:
      srsnet:
          ipv4_address: "172.18.0.4"

  ue1:
    build:
      context: .
      dockerfile: ./Dockerfile_ue
    image: naposto/srsue
    container_name: ue1
    privileged: true
    depends_on:
      - enb1
    volumes:
      - type: bind
        source: ./test/docker_files/ue.conf
        target: /conf/ue.conf
    networks:
      srsnet:
        ipv4_address: "172.18.0.5"

  ue2:
    build:
      context: .
      dockerfile: ./Dockerfile_ue
    image: naposto/srsue
    container_name: ue2
    privileged: true
    depends_on:
      - enb1
    volumes:
      - type: bind
        source: ./test/docker_files/ue2.conf
        target: /conf/ue.conf
    networks:
        srsnet:  
          ipv4_address: "172.18.0.6"
  
  ue3:
    build:
      context: .
      dockerfile: ./Dockerfile_ue
    image: naposto/srsue
    container_name: ue3
    privileged: true
    depends_on:
      - enb2
    volumes:
      - type: bind        
        source: ./test/docker_files/ue3.conf
        target: /conf/ue.conf
    networks:
        srsnet:
            ipv4_address: "172.18.0.7"

  ue4:
    build:
      context: .
      dockerfile: ./Dockerfile_ue
    image: naposto/srsue
    container_name: ue4
    privileged: true
    depends_on:
      - enb2
    volumes:
      - type: bind        
        source: ./test/docker_files/ue4.conf
        target: /conf/ue.conf
    networks:
        srsnet:
            ipv4_address: "172.18.0.8"

networks:
  srsnet:
    name: srsnet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"


      

