ARG UBUNTU_VERSION=bionic
ARG SRSLTE_RELEASE_TAG=release_20_10_1

FROM ubuntu:${UBUNTU_VERSION} as builder
ARG UBUNTU_VERSION
ARG SRSLTE_REPO=https://github.com/srsLTE/srsLTE
ARG SRSLTE_CHECKOUT=${SRSLTE_RELEASE_TAG}

RUN apt update \
    && apt install -y \
    build-essential \
    git \
    cmake \
    libfftw3-dev \
    libmbedtls-dev \ 
    libboost-program-options-dev \
    libconfig++-dev \
    libsctp-dev \ 
    libzmq3-dev \
 && mkdir /srslte \
 && cd /srslte \
 && git clone $SRSLTE_REPO srslte \
 && cd srslte \
 && git checkout ${SRSLTE_CHECKOUT} \
 && mkdir build \
 && cd build \
 && cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/srslte -DENABLE_SRSUE=OFF -DENABLE_SRSEPC=OFF ../ \
 && make \
 && make install \
 && ./srslte_install_configs.sh user

FROM ubuntu:${UBUNTU_VERSION}
ARG UBUNTU_VERSION

RUN apt update \
 && apt install -y \
        libfftw3-dev \
        libmbedtls-dev \ 
        libboost-program-options-dev \
        libconfig++-dev \
        libsctp-dev \ 
        libzmq3-dev

COPY --from=builder /opt/srslte /opt/srslte
COPY --from=builder /root/.config/srslte/ /root/.config/srslte/ 

ENV LD_LIBRARY_PATH /opt/srslte/lib:$LD_LIBRARY_PATH
ENV PATH /opt/srslte/bin:$PATH

CMD ["srsenb", "--enb_files.rr_config", "/conf/rr.conf", "/conf/enb.conf"]
